### ISSUE TITLE
Speed estimation 

### ISSUE THREAD

**Issue by assalas06-bejaia** [swhan0329/tracking_and_speed_estimation#1]
Hi dear ,
Can you tell me about the average error of the speed estimation for this method ,and if I can Apply this method of Unmaned aerial vehicles ?your FPS ?and which version of python did you used ? 
Thank you in advance

**Comment by swhan0329** [comment]
@assalas06-bejaia 
Thank you for your interest.
1. I didn't evaluate this method. Because at that time, I don't have GT data of vehicle speed. And I just want to let you know this method.
2. I think there is a problem if you apply this method to UAV. You cannot get real distance using lane length on the road. If there is a solution of that, you can use this algorithm.
3. Maybe 10~15FPS I think. But this is not a exactly number.
4. I used python 3.6.
